[package]
name = "rs-9cc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
uuid = { version = "1.6.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
